### ISSUE TITLE
`backwardsScan` + `replace` produces incorrect results

### ISSUE THREAD

**Issue by pkese** [atom/text-buffer#111]
Hi, 

In javascript, the classic string replace function works as follows:

    "foo \n bar \r\n baz".replace(/\r?\n/g, '\r\n')
    > "foo \r\n bar \r\n baz"

whereas with TextBuffer the result is as follows:

    buffer = new TextBuffer("foo \n bar \r\n baz")
    buffer.backwardsScan( /\r?\n/g, match => match.replace('\r\n') )
    > "foo \n bar \n baz"

(...even more interesting things happen when replacing `/$/g`)

I have found this issue as I was exploring why suddenly my `editorconfig` stopped working in sindresorhus/atom-editorconfig#54

Can someone please have a look at this or help me understand if my issue with `editorconfig` is related to this.

**Comment by lierdakil** [comment]
A quick update to my musings in https://github.com/atom/atom/issues/10075.

I did a little more digging through commit history, and apparently https://github.com/atom/text-buffer/commit/2c58da288aefccc3a8b4d27147eae6b5630fe2e2 is the real culprit. Reverting this commit on `src/match-iterator.coffee` fixes everything. Besides, test introduced in this commit passes without other associated changes. I'm not sure what changed since then, but this commit seems unnecessary now? /cc @nathansobo
