### ISSUE TITLE
Implementing capture groups

### ISSUE THREAD

**Issue by mkatychev** [atom/text-buffer#304]
Hi there, is there a way to implemented capture groups in a method similar to the find-and-replace functionality?
```coffeescript
atom.commands.add 'atom-text-editor', 'custom:trim-odd-spaces', ->
  buffer = atom.workspace.getActiveTextEditor().getBuffer()
  regMatch = /^ (( {2})*\S)/g  #match any odd numbered spaces followed by text
  buffer.backwardsScan(regMatch, (match) -> match.replace( '$1'))
```
this snippet interprets `$1` as a literal string.

**Comment by rsese** [comment]
Thanks for reaching out!

Just wanted to let you know that though one of the maintainers might chime in here, the best places for questions are detailed below so I'm going to go ahead and close this.  People on the Atom Slack and the message board in particular are super helpful with these types of questions (I don't know the answer myself unfortunately).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
